// Generated by N4JS transpiler; for copyright see original N4JS source file.

(function(System) {
	'use strict';
	System.register([], function($n4Export) {
		var C;
		C = function C() {};
		$n4Export('C', C);
		return {
			setters: [],
			execute: function() {
				$makeClass(C, N4Object, [], {}, {}, function(instanceProto, staticProto) {
					var metaClass = new N4Class({
						name: 'C',
						origin: 'org.eclipse.n4js.spec.tests',
						fqn: 'Ch09_02_04__ImportStatements.N4JS1.C',
						n4superType: N4Object.n4type,
						allImplementedInterfaces: [],
						ownedMembers: [],
						consumedMembers: [],
						annotations: []
					});
					return metaClass;
				});
			}
		};
	});
})(typeof module !== 'undefined' && module.exports ? require('n4js-node').System(require, module) : System);
//# sourceMappingURL=N4JS1.map
