#!/usr/bin/env groovy
/*
 * Copyright (c) 2017 NumberFour AG.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *   NumberFour AG - Initial API and implementation
 */

import org.codehaus.groovy.runtime.DefaultGroovyMethods

try {

	timestamps {

	node ("docker-spec") {
		currentBuild.result = "SUCCESS"

		def workspace = pwd()
		def sourceX = "sourceX"
		def sourceBranch = env.BRANCH

		def htmlDir="$WORKSPACE/${sourceX}/docs/www/web-html"
		def specDir="$WORKSPACE/${sourceX}/docs/org.eclipse.n4js.spec"

		def String buildhtml = env.BUILD_URL+"execution/node/5/ws/sourceX/docs/www/web-html"

		sh "pwd; ls -la"

		stage('Cleanup') {
			dir( sourceX ) {
			    deleteDir()
			}
		}

		dir( sourceX ) {

			stage('Source Checkout') {
				sh "git clone --depth 1 -b $sourceBranch https://github.com/eclipse/n4js.git ."
			}
			
			stage ('Build Eclipse Web Pages') {

				dir ('docs/www') {
					sh "${workspace}/${sourceX}/docs/www/buildweb.sh --docker"
				}
				echo "\u2705 Build successful."

			}

			stage ('Build N4JS Specification') {
				sh "cp -r $WORKSPACE/${sourceX}/docs/www/assets/. $specDir/"
				sh "docker run --rm --user `id -u`:`id -g` -t -e DOC_NAME=N4JSSpec -v \$(pwd)/docs/org.eclipse.n4js.spec:/workspace:rw docker.corp.numberfour.eu/numberfour/asciispec:0.0.10 -a"
				echo "\u2705 Build successful."
			}	
		}

		stage ('Aggregating Web Pages') {
			sh "cp -r $specDir/generated-docs/. $WORKSPACE/${sourceX}/docs/www/web-html/spec"
			echo "On branch $sourceBranch - HTML can be viewed in Job ${env.BUILD_NUMBER} workspace: $buildhtml"
			echo "\u2705 Aggregation finished."
		}
	}} // close try & timestamp
}

catch (exc) {
	currentBuild.result = "FAILURE"
	echo "Caught: ${exc}"
	// Email notification temporarily disabled
	//echo "[ERROR]\u274C ${sourceBranch} failing. Sending email notification."
    //sendEmail( "${env.JOB_NAME} (${env.BUILD_NUMBER}) failed", "${env.BUILD_URL} is failing - ${env.JOB_NAME} (#${env.BUILD_NUMBER}). The following exception was caught : \n ${exc.toString()}")
}

/**
 * Sends email notification about job status based on the provided data.
 *
 * @param subject the subject of the email
 * @param body the body of the email
 */
@NonCPS
void sendEmail(String subject, String body) {
        emailext subject: subject,
                body: body,
                recipientProviders: [
                        [$class: 'CulpritsRecipientProvider'],
                        [$class: 'RequesterRecipientProvider']]
}

// vim: ft=groovy
