////
Copyright (c) 2016 NumberFour AG.
All rights reserved. This program and the accompanying materials
are made available under the terms of the Eclipse Public License v1.0
which accompanies this distribution, and is available at
http://www.eclipse.org/legal/epl-v10.html

Contributors:
  NumberFour AG - Initial API and implementation
////

= Help System

[[sec:Built_In_Help]]
== Built-In Help

[[sec:Context_Sensitive_Help]]
== Context Sensitive Help

[[sec:Cheat_Sheets]]
== Cheat Sheets

[[sec:JSDoc]]
== JSDoc


[[sec:Hovering]]
== Hovering

Hovering over an element (such as type, field, method, function or variable declaration) in the N4JS editor will cause a tooltip appear containing information about the underlying element. Currently this information is the type (could be the inferred type as well), the name and the keyword (such as class, variable, field) of the actual element. By default the tooltip does not grab the focus from the currently active workbench window and will automatically disappear after the focus is lost from the element. One can grab the focus for the tooltip by clicking into the tooltip area or pressing kbd:[F2] function key.

[[sec:Show_Type_Information_of_Selection]]
=== Show Type Information of Selection

In some cases, during the development process, one would like to know what is the actual or even the inferred type of an N4JS expression. To use this functionality one can select the desired expression in the editor and invoke the ’Show Type Information’ command via the kbd:[Cmd] + kbd:[Option]+ kbd:[I] ( kbd:[Ctrl] + kbd:[Alt]+ kbd:[I] Windows/Linux) from the keyboard. This case a popup window will be raised containing the type information of the actual selection.

[[sec:Show_MDN_Documentation_of_Build-In_Types]]
=== Show MDN Documentation of Build-In Types

Hovering over a known type or its properties/methods in the N4JS editor will cause a tooltip appear containing a link to their MDN (Mozilla Developer Network) counterpart.

[[sec:Example_Projects_and_Files]]
== Example Projects and Files
