// Generated by N4JS transpiler; for copyright see original N4JS source file.

Object.defineProperty(exports, "__esModule", { value: true });

const net = require("net");
const VSCode = require("vscode");
const VSCodeJRCP = require("vscode-jsonrpc");
const VSCodeLC = require("vscode-languageclient");
function activate(context) {
	let serverOptions = ()=>{
		let socket = net.connect({
			port: 5007
		});
		let result = {
			writer: socket,
			reader: socket
		};
		return Promise.resolve(result);
	};
	let clientOptions = {
		documentSelector: [
			'n4js'
		],
		synchronize: {
			fileEvents: VSCode.workspace.createFileSystemWatcher('**/*.*')
		}
	};
	let lc = new VSCodeLC.LanguageClient('N4JS Language Server', serverOptions, clientOptions);
	lc.trace = VSCodeJRCP.Trace.Verbose;
	let disposable = lc.start();
	context.subscriptions.push(disposable);
}


exports.activate = activate;
//# sourceMappingURL=extension.map
