// Generated by N4JS transpiler; for copyright see original N4JS source file.

(function(System) {
	'use strict';
	System.register([], function($n4Export) {
		var ITestReporter;
		ITestReporter = {};
		$n4Export('ITestReporter', ITestReporter);
		return {
			setters: [],
			execute: function() {
				ITestReporter.$fieldInit = function ITestReporter_fieldInit(spec, mixinExclusion) {
					if (spec) {
						if (!(mixinExclusion.hasOwnProperty('spy') || this.hasOwnProperty('spy'))) {
							this.spy = 'spy' in spec ? spec.spy : undefined;
						}
					} else {
						if (!(mixinExclusion.hasOwnProperty('spy') || this.hasOwnProperty('spy'))) {
							this.spy = undefined;
						}
					}
				};
				ITestReporter.$methods = {};
				$makeInterface(ITestReporter, function(instanceProto, staticProto) {
					var metaClass = new N4Interface({
						name: 'ITestReporter',
						origin: 'org.eclipse.n4js.mangelhaft',
						fqn: 'org.eclipse.n4js.mangelhaft.types.ITestReporter.ITestReporter',
						n4superType: undefined,
						allImplementedInterfaces: [],
						ownedMembers: [
							new N4DataField({
								name: 'spy',
								isStatic: false,
								annotations: []
							}),
							new N4Method({
								name: 'register',
								isStatic: false,
								jsFunction: instanceProto['register'],
								annotations: []
							})
						],
						consumedMembers: [],
						annotations: []
					});
					return metaClass;
				});
			}
		};
	});
})(typeof module !== 'undefined' && module.exports ? require('n4js-node/src-gen/index').System(require, module) : System);
//# sourceMappingURL=ITestReporter.map
