// Generated by N4JS transpiler; for copyright see original N4JS source file.

(function(System) {
	'use strict';
	System.register([], function($n4Export) {
		var TestError;
		TestError = function TestError(message) {
			var err = new Error(message);
			this.message = err.message;
			this.name = this.constructor.n4type.name;
			Object.defineProperty(this, 'stack', { get: function() { return err.stack; }, set: function(value) { err.stack = value; } });
		};
		$n4Export('TestError', TestError);
		return {
			setters: [],
			execute: function() {
				$makeClass(TestError, Error, [], {}, {
					throw: {
						value: function throw___n4(message) {
							throw new TestError(message);
						}
					}
				}, function(instanceProto, staticProto) {
					var metaClass = new N4Class({
						name: 'TestError',
						origin: 'org.eclipse.n4js.mangelhaft',
						fqn: 'org.eclipse.n4js.mangelhaft.types.TestError.TestError',
						n4superType: undefined,
						allImplementedInterfaces: [],
						ownedMembers: [
							new N4Method({
								name: 'throw',
								isStatic: true,
								jsFunction: staticProto['throw'],
								annotations: []
							})
						],
						consumedMembers: [],
						annotations: []
					});
					return metaClass;
				});
			}
		};
	});
})(typeof module !== 'undefined' && module.exports ? require('n4js-node').System(require, module) : System);
//# sourceMappingURL=TestError.map
