////
Copyright (c) 2016 NumberFour AG.
All rights reserved. This program and the accompanying materials
are made available under the terms of the Eclipse Public License v1.0
which accompanies this distribution, and is available at
http://www.eclipse.org/legal/epl-v10.html

Contributors:
  NumberFour AG - Initial API and implementation
////

:doctype: book
:notitle:

.N4JS Articles
= N4JS Articles

.A selection of articles covering the features of N4JS, Current Releases, how to report bugs and contribute to the platform.

== Index

* <<../features/index.adoc#n4js-language-and-ide-features,Feature Table>> - A comprehensive overview of current and planned features the N4JS IDE has to offer.
* <<../features/async-await.adoc#async-await,Async/Await>> - Learn about the benefits of asynchronous data flows and how they work with N4JS code.
* <<../features/dependency-injection.adoc#dependency-injection-in-n4js,Dependency Injection>> - Configure dependencies between classes with built-in Dependency Injection support.
* <<../features/modules.adoc#modules,Modules>> - Modules help keep code well-defined and easy to comprehend. Read about keeping large projects maintainable with Module support within the N4JS IDE.
* <<../features/nodejs-support.adoc#node-js-support,Node.js Support>> - Seamless integration of N4JS projects with existing node.js-based environments.
* <<../features/nominal-and-structural-typing.adoc#nominal-and-structural-typing,Nominal & Structural Typing>> - N4JS provides both forms of typing. Read the feature on how they are combined in N4JS.
* <<../features/testing.adoc#testing,Testing>> - The N4JS IDE and the built-in test execution runtime Mangelhaft were designed from the ground-up to support Test Driven Development. Explore how testing with N4JS will help ensure your projects behave as expected.

***

**Releases**

* <<../releases/index.adoc#releases,Information on N4JS Releases>> - The current release of N4JS, version 0.3, is a "public alpha". This article details what that means, the current state of N4JS and how we track issues.
* <<../releases/reporting-bugs.adoc#reporting-bugs,Reporting Bugs>> - Find out how to report N4JS bugs within the IDE itself with Xpect.

***

**FAQ**

* <<../faq/index.adoc#faq,Frequenctly Asked Questions>> -Common N4JS topics such as Open-Sourcing, JavaScript, Java and Typescript Comparison/
* <<../faq/comparison-java.adoc#n4js-and-java,N4JS & Java Comparison>> - A comparison between the features of N4JS and Java.
* <<../faq/comparison-typescript.adoc#n4js-and-typescript,N4JS & Typescript Comparison>> - A comparison between the features of N4JS and Typescript.

***

**N4JS Userguides**


From brief quickstart guides to fully-involved tutorials, the following N4JS documentation will help beginners get started with the N4JS IDE and advanced users to build and maintain large server-side projects.

* <<../userguides/index.adoc#index,Userguides Index>>
* <<../userguides/ide-setup.adoc#_ide_setup,N4JS IDE Setup Guide>> - Basic installation and setup instructions.
* <<../userguides/npm-export-guide.adoc#_npm_export_guide,npm Export Guide>> - Basic npm export and publishing instructions.
* <<../userguides/tutorial.adoc#_tutorial,In-Depth Tutorial>> - Begin using the more powerful features N4JS has to offer!
