// Generated by N4JS transpiler; for copyright see original N4JS source file.

(function(System) {
	'use strict';
	System.register([], function($n4Export) {
		var SVDemo;
		SVDemo = function SVDemo() {};
		$n4Export('SVDemo', SVDemo);
		return {
			setters: [],
			execute: function() {
				$makeClass(SVDemo, N4Object, [], {
					foo: {
						value: function foo___n4() {
							console.log("Hello World");
						}
					}
				}, {}, function(instanceProto, staticProto) {
					var metaClass = new N4Class({
						name: 'SVDemo',
						origin: 'SVDemo',
						fqn: 'pac.SVDemo.SVDemo',
						n4superType: N4Object.n4type,
						allImplementedInterfaces: [],
						ownedMembers: [
							new N4Method({
								name: 'foo',
								isStatic: false,
								jsFunction: instanceProto['foo'],
								annotations: []
							})
						],
						consumedMembers: [],
						annotations: []
					});
					return metaClass;
				});
			}
		};
	});
})(typeof module !== 'undefined' && module.exports ? require('n4js-node').System(require, module) : System);
//# sourceMappingURL=SVDemo.map
