////
Copyright (c) 2018 NumberFour AG.
All rights reserved. This program and the accompanying materials
are made available under the terms of the Eclipse Public License v1.0
which accompanies this distribution, and is available at
http://www.eclipse.org/legal/epl-v10.html

Contributors:
  NumberFour AG - Initial API and implementation
////

= Release Engineering

== Build the N4JS IDE from command line

Ensure you have

- Java 8
- Maven 3.2.x and
- Node.js 6

installed on your system.

Clone the repository

----
git clone https://github.com/Eclipse/n4js.git
----

Change to the n4js folder:
----
cd n4js
----

Run the Maven build:
----
mvn clean verify
----

You may have to increase the memory for maven via `export MAVEN_OPTS="-Xmx2048m"` (Unix) or `set MAVEN_OPTS="-Xmx2048m"` (Windows).

=== Publish maven-tooling `org.eclipse.n4js.releng.util`

NOTE: For extending the N4JS-language in a different project, the `org.eclipse.n4js.releng.util` module needs to be published as a maven-plugin. You can deploy this SNAPSHOT-artifact to a local folder by providing the `local-snapshot-deploy-folder`-property pointing to an absolute path in the local file system:

----
mvn clean deploy -Dlocal-snapshot-deploy-folder=/var/lib/my/folder/local-mvn-deploy-repository
----

The existence of `local-snapshot-deploy-folder` will trigger a profile enabling the deploy-goal for the project `org.eclipse.n4js.releng.util`