////
Copyright (c) 2018 NumberFour AG.
All rights reserved. This program and the accompanying materials
are made available under the terms of the Eclipse Public License v1.0
which accompanies this distribution, and is available at
http://www.eclipse.org/legal/epl-v10.html

Contributors:
  NumberFour AG - Initial API and implementation
////

= Release Engineering

[[sec:overview_of_published_artifacts]]
== Overview of Published Artifacts

The main published artifacts are:

* the headless builder, i.e. n4jsc.jar,
  published to `download.eclipse.org` (see https://download.eclipse.org/n4js/),
* the N4JS libraries (or "n4js-libs", for short), including the N4JS runtime libraries and
  the 'mangelhaft' test framework (i.e. the projects in folder `n4js-libs/packages`),
  published to the official public npm registry at https://www.npmjs.com/,
* an LSP extension for Visual Studio Code, available at
  https://marketplace.visualstudio.com/items?itemName=n4js.n4js-vscode-extension.

Other published artifacts include various documentation and the N4JS web site.


[[sec:versioning]]
== Versioning

=== Example

The main published artifacts (see <<sec:overview_of_published_artifacts>>) are versioned
as follows:

[cols="10,6,1"]
|===
| Language Version (applies to n4jsc.jar as well) | Version of n4js-libs      | Note

| n4js-ide_macos_0.14.20.v20190912-0200.dmg       | 0.14.20                   |
| n4js-ide_macos_0.14.20.v20190913-0200.dmg       |                           | 1.
| n4js-ide_macos_0.14.20.v20190914-0200.dmg       |                           |
| n4js-ide_macos_0.14.21.v20190915-0200.dmg       | 0.14.21                   | 2.
| n4js-ide_macos_0.14.21.v20190916-0200.dmg       |                           |
| n4js-ide_macos_0.15.0.next_v20190916-1422.dmg   | 0.15.0-next.20190916.1422 | 3.
| n4js-ide_macos_0.14.21.v20190917-0200.dmg       |                           | 
| n4js-ide_macos_0.15.0.next_v20190917-1138.dmg   | 0.15.0-next.20190917.1138 |
| n4js-ide_macos_0.14.21.v20190918-0200.dmg       |                           |
| n4js-ide_macos_0.15.0.v20190919-0200.dmg        | 0.15.0                    | 4.
| n4js-ide_macos_0.15.0.v20190920-0200.dmg        |                           |
|===

Notes:

1. New IDE published for unchanged version 0.14.20 of n4js-libs.
2. When publishing a new version of n4js-libs, the major/minor/patch segment of the IDE is increased accordingly.
3. Experimental publishing of breaking changes in n4js-libs with a pre-release tag and npm dist-tag 'next'.
   The tag is also prepended to the last segment of the IDE version.
   NOTE: since the version scheme of maven/OSGi does not support something like semver's pre-release tags,
   these IDE versions must not be published to any public registries!
4. Release of the breaking changes from release channel 'next' to release channel 'latest'.


=== Configuring Versioning

The developer can conveniently control versioning via file `version.json`:

* When introducing non-breaking changes in the n4js-libs, nothing has to be changed in `version.json`;
  version increments will be computed automatically by incrementing the patch segment.
* When introducing breaking changes in the n4js-libs, edit file `version.json` to request an
  increment of the major/minor segment.
* In any case, if publishing from a topic branch is desired for testing purposes before merging
  to master, simply configure a "tag" in file `version.json` and run the publishing build from
  that branch. This will publish the n4js-libs under an npm dist-tag and publish the other
  artifacts to separate folders (and won't change the LATEST folders).
  NOTE: don't forget to set property "tag" back to an empty string in `version.json` before merging to master.

In case of breaking changes only in the Java / Xtend code of the core language (IDE or headless builder)
we do not yet increment any versions except updating time stamps, so file `version.json` does not have
to be changed in this case.


=== Details of Version Computation

The versioning of all the main published artifacts (see <<sec:overview_of_published_artifacts>>)
is controlled by shell script `compute-version.sh`. This script will compute the correct, incremented
version of the currently running build and write all version-related information to a newly
created file `version-info.json` in the root folder of the repository. In addition, it will update
the place-holder version in file `plugins/org.eclipse.n4js/res/language-version.properties` to make
the version number available to the Java code at runtime. Actual publishing will then be performed
by script `publish-n4js-libs.sh` (for the n4js-libs) and by plain file copying in the Jenkinsfile
`eclipse-publish.jenkinsfile` of the publishing build (for the `n4jsc.jar` and the IDE products).

The logic for finding the correct, incremented version number for a currently running build
applied by script `compute-version.sh` is as follows:

1. As a basis for the current build's version number, use the major, minor, and patch segments
   of the newest version of the n4js-libs available on `npmjs.org` for the dist-tag `latest`.
2. Check whether a new version of the n4js-libs has to be published to `npmjs.org` by the current
   build. This is the case of the current commit ID of top-level folder `n4js-libs` of the local
   git working copy differs from the commit ID of the newest version of the n4js-libs available
   on `npmjs.org` for the dist-tag `latest`.
3. If a new version of n4js-libs has to be published, increment the major, minor, or patch segment(s)
   depending on the configuration in `version.json`.
   Otherwise, don't increment these segments.
4. Now, versions used for publishing are:
   a. For publishing the n4js-libs, use the major, minor, patch segment resulting from step 3.
   b. For publsihing the headless builder and the IDE products, use the major, minor, patch segment
      resulting from step 3 and append a time stamp segment.


== Nightly build on Eclipse infrastructure

The N4JS IDE, headless n4jsc.jar, and the N4JS update site is being built on the Eclipse Common Build
Infrastructure (CBI). For this purpose the N4JS project is using a dedicated Jenkins instance, referred
to as a "Jenkins Instance Per Project" (JIPP) in Eclipse CBI documentation. At this time, the N4JS
project's JIPP is running on the "old" infrastructure, not yet using docker. This will be migrated
at a later point in time.

The N4JS JIPP is available at: https://ci.eclipse.org/n4js/

The nightly build performs the following main steps:

1. compile the N4JS implementation,
2. build the n4jsc.jar, the IDE products for MacOS, Windows, Linux, and the update site,
3. run tests,
4. sign the IDE product for macOS and package it in a .dmg file,
5. deploy to n4jsc.jar, IDE products and update sites to Eclipse download server (i.e. download.eclipse.org),
6. move all artifacts older than 7 days from download.eclipse.org to archive.eclipse.org.

Details about all the above steps can be found in the Jenkinsfile `eclipse-nightly.jenkinsfile`, located in
the root folder of the N4JS source repository on GitHub.

The most accurate documentation for our JIPP can be found at https://wiki.eclipse.org/IT_Infrastructure_Doc.
Note that many other documents do not apply to our JIPP, at the moment, as they refer to the new
infrastructure, e.g. https://wiki.eclipse.org/CBI and https://wiki.eclipse.org/Jenkins.

=== Build on other machines

There is a blog post https://jevopisdeveloperblog.blogspot.com/2019/10/setup-github-triggered-build-machine.html describing how to set up a Github triggered build machine for Eclipse N4JS. This post describes in detail how to set up Jenkins and necessary tools.

== Build the N4JS IDE from command line

Ensure you have

- Java 11
- Maven 3.2.x and
- Node.js 8

installed on your system.

Clone the repository

----
git clone https://github.com/Eclipse/n4js.git
----

Change to the n4js folder:
----
cd n4js
----

Run the Maven build:
----
mvn clean verify
----

You may have to increase the memory for maven via `export MAVEN_OPTS="-Xmx2048m"` (Unix) or `set MAVEN_OPTS="-Xmx2048m"` (Windows).

Available optional maven profiles are:

[horizontal]
execute-plugin-tests::          run OSGi tests (without UI)
execute-plugin-ui-tests::       run UI-based OSGi tests
execute-ecmas-tests::           run ECMA test suite
execute-smoke-tests::           run generated tests using corrupted source code as input
execute-accesscontrol-tests::   run generated tests for checking accessibility of class/interface members
execute-hlc-integration-tests:: run integration tests using the headless jar (requires docker!)

Available system properties:

[horizontal]
noTests::               if defined (i.e. "-DnoTests"), suppress execution of all tests
languageVersion::       an optional version string to show in the Eclipse About dialog of IDE products (should be defined by publishing builds)
startAndKeepVerdaccio:: if defined (i.e. "-DstartAndKeepVerdaccio"), enforce starting and suppress stopping of the test verdaccio (see <<sec:test-verdaccio>>)



=== Publish maven-tooling `org.eclipse.n4js.releng.util`

NOTE: For extending the N4JS-language in a different project, the `org.eclipse.n4js.releng.util` module needs to be published as a maven-plugin. You can deploy this SNAPSHOT-artifact to a local folder by providing the `local-snapshot-deploy-folder`-property pointing to an absolute path in the local file system:

----
mvn clean deploy -Dlocal-snapshot-deploy-folder=/var/lib/my/folder/local-mvn-deploy-repository
----

The existence of `local-snapshot-deploy-folder` will trigger a profile enabling the deploy-goal for the project `org.eclipse.n4js.releng.util`



[[sec:test-verdaccio]]
=== Test Verdaccio containing n4js-libs

If profile `execute-hlc-integration-tests` is active, a local verdaccio instance is started and populated with
freshly-compiled n4js-libs (the libraries located under top-level folder `/n4js-libs`) and is stopped before the
end of the build. The verdaccio instance is started as a docker container called `n4js-test-verdaccio`.

When giving `-DstartAndKeepVerdaccio` on the command line, such a test verdaccio will always be started/populated but
never stopped, regardless of whether profile `execute-hlc-integration-tests` is active or not. This is useful to enforce
starting of the test verdaccio (even without running integration tests) and then reusing it in subsequent builds.



=== Generation of Eclipse help for spec and design document

The HTML pages for N4JSSpec and N4JSDesign documents are generated from the Asciidoc sources in the project `org.eclipse.n4js.spec` `org.eclipse.n4js.design` by Asciispec. 

[[img:eclipse-help-doc-process]]
.The process of creating Eclipse help for N4JSSpec
image::{find}images/eclipse-help-process.svg[Creating Eclipse help for N4JSSpec]

Figure <<img:eclipse-help-doc-process>> shows the generation process for N4JSSpec document. The process for N4JSDesign (and other adoc documents) is the same. The following explains the diagram.

* `Asciispec` is used to compile the source N4JSSpec Asciidoc into a single large `N4JSSpec.html` file which contains all the chapters. The use of the custom parameter `-a eclipse-help-mode` indicates that a special header and footer styles as well as CSS style should be used (i.e. no table of content menu, no download links etc.). Here, we are using the possibility provided by Asciidoctor to configure header/footer as well as CSS style via parameter `:docinfodir:` and `:stylesheet:`.
* Our custom tool `Chunker` splits `N4JSSpec.html` (and other documents) into multiple chunked HTML files, each of which corresponds to either the `index` file or a chapter. It automatically re-writes internal links.
* Another custom tool `EclipseHelpTOCGenerator` takes to Docbook file `N4JSSpec.xml` and generates an XML file describing the table of content (TOC) in the Eclipse format. This TOC file references the chunked HTML files above.
* Another custom tool `IndexTocGenerator` takes to Docbook file `N4JSSpec.xml` similar to `EclipseHelpTOCGenerator`, but it generates an HTML fragment which can be embedded into the `index.html` page generated by the `Chunker` (Thus it has to run before the Chunker in that case).


== Updating frameworks and dependencies

=== Update of Eclipse, EMF, Xtext, etc.

For updating the N4JS IDE to a new version of Eclipse, EMF, Xtext, etc. follow these steps:

. Create a new branch.
. Bump versions of all dependencies mentioned in file `N4JS.setup`:
.. Update all labels that refer to the version of the Ooomph setup (search for "label!" to find them).
.. Choose a new Eclipse version and define this in `N4JS.setup` (c.f. `repositoryList`).
.. For those other dependencies _that come with Eclipse_ (e.g. EMF, Xtext) find out which version matches the chosen Eclipse version
   and define that version in `N4JS.setup`. +
   Tip: use the contents list of the SimRel you are targeting, e.g. https://projects.eclipse.org/releases/2019-03
.. For those other dependencies _that are available via the Eclipse Orbit_, find out which version is the latest version available in
   the Orbit and define that version in `N4JS.setup`. +
   Tip: contents of the Eclipse Orbit can be found at https://download.eclipse.org/tools/orbit/downloads/ +
   (choose the correct link for the chosen Eclipse version!)
.. For all remaining dependencies (i.e. unrelated to Eclipse and not in Orbit), choose a version to use and define it in `N4JS.setup`.
. Check `Require-Bundle` sections of MANIFEST.MF files by searching for related bundle names or for `;bundle-version="`:
.. There should be at most one version constraint for a specific bundle +
   NOTE: the version constraints in the MANIFEST.MF files are just lower bounds and - at this time - we do not bump them to the latest version, in most cases.
.. There should be no version constraints to our bundles (i.e. `org.eclipse.n4js...`)
. Review parent pom.xml files, i.e. `releng/org.eclipse.n4js.parent/pom.xml`:
.. Update property `xtext-version`.
.. Check all other `*-version` properties and update them where needed.
. Update target platform file `org.eclipse.n4js.targetplatform.target` using Ooomph's auto-generation:
.. Start the Eclipse Installer.
.. Update the Eclipse Installer (using the button with the turning arrows).
.. On the second page, add the `N4JS.setup` file from your branch to the Eclipse Installer, using a GitHub raw(!) URL: +
   `https://raw.githubusercontent.com/eclipse/n4js/BRANCH_NAME/releng/org.eclipse.n4js.targetplatform/N4JS.setup`
.. Ooomph a new development environment with this setup.
.. In the new Eclipse workspace created by Ooomph, the target platform file should have uncommitted changes:
... carefully review these changes, to be sure they make sense, and then
... commit & push those changes to your branch.
. Make sure file `builds/org.eclipse.n4js.product.build/signing-entitlements.xml` is still up-to-date with its
  source file (see link to source file at top of `signing-entitlements.xml`).
. Thoroughly test the new versions, including some manual(!) tests:
.. Run Jenkins builds.
.. Ooomph another N4JS development environment with Eclipse Installer.
   This time, after Ooomphing is completed, the target platform file should no longer have any uncommitted changes.
.. Ensure the following types of tests can be executed locally in the newly installed Eclipse:
... plain JUnit tests (e.g. `org.eclipse.n4js.lang.tests`).
... Plugin tests.
... Plugin UI tests.
... Xpect tests (individual files and entire bundles; e.g. `org.eclipse.n4js.spec.tests`).
... Xpect UI tests.
.. Ensure an N4JS IDE product can be launched from within the newly installed Eclipse using the launch configuration
   provided in the n4js repository.
.. After launching the N4JS IDE product, refresh the workspace and review/commit any changes in file `N4JS__IDE.launch`. 
.. Download a product created in a Jenkins CI build and test it manually.
.. After merging to master: download the products created in an Eclipse nightly build and test them manually.
... Ensure signing and JRE bundling are still working properly.
... Ensure that both the .zip- and .dmg-archives can be extracted and produce working executables / app-bundles.
    On macOS, extracting the .zip by double-clicking it in Finder must work!

All the above steps need to be performed in the `n4js-extended` repository, accordingly (e.g. file `N4JS-Extended.setup`).


=== Update of the embedded JRE

For updating the embedded JRE inside the N4JS IDE follow these steps:

. Given a new JRE download location for Linux, MacOS and Windows with a common new version
. Update the location related properties in the pom.xml files of
.. n4js/builds/pom.xml
.. n4js/builds/org.eclipse.n4js.jre.linux.gtk.x86_64/pom.xml
.. n4js/builds/org.eclipse.n4js.jre.macosx.cocoa.x86_64/pom.xml
.. n4js/builds/org.eclipse.n4js.jre.win32.win32.x86_64/pom.xml
. Update the versions at all following locations:
.. n4js/builds/org.eclipse.n4js.jre.linux.gtk.x86_64/META-INF/MANIFEST.MF
.. n4js/builds/org.eclipse.n4js.jre.linux.gtk.x86_64/META-INF/p2.inf
.. n4js/builds/org.eclipse.n4js.jre.macosx.cocoa.x86_64/META-INF/MANIFEST.MF
.. n4js/builds/org.eclipse.n4js.jre.macosx.cocoa.x86_64/META-INF/p2.inf
.. n4js/builds/org.eclipse.n4js.jre.win32.win32.x86_64/META-INF/MANIFEST.MF
.. n4js/builds/org.eclipse.n4js.jre.win32.win32.x86_64/META-INF/p2.inf
. Update the openjdk docker image used as base image in the "FROM" line at the top of all docker files:
.. n4js-extended/jenkins/docker-build/Dockerfile
