////
Copyright (c) 2019 NumberFour AG and others.
All rights reserved. This program and the accompanying materials
are made available under the terms of the Eclipse Public License v1.0
which accompanies this distribution, and is available at
http://www.eclipse.org/legal/epl-v10.html

Contributors:
  NumberFour AG - Initial API and implementation
////


[[sec:Views]]
= Views
:find:

This section briefly introduces all the views that belong to the application’s default perspective.

== Eclipse Standard Views

In the following we descibe views usually available in Eclipse based IDEs. Some of the views were slightly adjusted to match specific N4JS needs.

[[sec:Project_Explorer_View]]
===  Project Explorer

The Project Explorer view shows the resources from the underlying workspace in a hierarchical way. From this view one can open a resource for editing in the associated editor or select it to perform an operation on the resource. A popup contest menu is available from the Project Explorer for each resources if used right clicks any of them. A lot of convenient actions are available for from the popping context menu: file modifications (such as Copy, Cut, Paste and Delete) and import/export. Project Explorer support file system modifications by drag-and-dropping resources. One can link the Project Explorer with the editors, if one enables the view-editor-linking then the node in the tree representing a particular resource in the workspace will be automatically revealed and highlighted once one activates the corresponding editor. This works the other way around as well, when a node is selected in the tree and the corresponding resource is opened in an editor, then the editor will be activated.

[[sec:Outline_View]]
===  Outline

The Outline view is responsible for displaying the outline of a structured file that is currently opened in an editor. In case of opening an N4JS file the view depicts all the types defined in the file. The owned members, functions and methods of a particular type are represented in a tree structure. Furthermore in case of opening an N4JS file in the editor, one can link the Outline view with the editor which means whenever one selects a node from the outline view the corresponding item will be revealed and highlighted in the editor.

[[sec:Problems_View]]
===  Problems

This view is used to show all validation errors and warnings in a table that are generated for workbench resources such as N4JS files. For instance when one writes and/or saves an N4JS file that contains validation errors and/or warnings those issues will be automatically logged into the Problems view. One can reveal the actual problem in the N4JS by simply double-clicking on the problem in the view. In this case the corresponding N4JS file will be opened (if it was not already opened), activated and the relevant line will be revealed in the editor. By default the grouping in the Problems view is done by the severity of the issues. One can group the issues by issue type or just disable the grouping at all. The first column of the table is the actual description of the issue for a particular resource. The second column names the problematic resource itself. The third column shows the relative path of the problematic resource. The location, fifth, column describes the problematic line in the resource. And last but not least the sixth column is for naming the type of the problem. This is optional and might be missing for some cases. One can customise the content of the view from the view menu. One can limit the number of revealed items in the table or can modify the behaviour of the content provider.

[[sec:Console_View]]
===  Console

The Console view is used to reveal a text based output provided by a running process and also allows user to provide any input to the running process from the keyboard.

[[sec:History_View]]
===  History

History view supports a way to track the changes of the workbench resources. This view also responsible for providing a convenient way to reveal historical revisions of a particular resource and it is even supports a mechanism to compare two different revisions of a resource. By default this view only provides local historical information but if a resource is under version control then one can retrieve revisions for that particular resource even it was made by remotely by another IDE user.

[[sec:Error_Log_View]]
===  Error Log

The Error Log view captures and logs all errors and warnings in a table generated by the application itself. Unlike Problems view the Error Log is responsible to collect and to reveal issues caused by a malfunctioned component or module of the IDE.


== N4JS Specific Views

The following views are specific to N4JS. Some of these views are useful for developers of the N4JS language itself as they reveal internal details at runtime. Most of these views can be opened via `Windows/Show View/Other..`, see `N4JS` category.

=== Test Results

The N4JS equivalent to the JUnit test view.

=== Source Graphs

Shows the AST, type model (ie. TModule), and the control flow graph of the current source code in the editor window.
The view is implemented in the bundle `org.eclipse.n4js.smith.graph`.

There are two ways for showing an AST / type model in the view:

Manually:: Open the view and an N4JS editor with some example code and click either the AST graph or the control flow graph button in the view.

Programmatically:: Open the view while debugging code, add a call to method `UtilN4.takeSnapshotInGraphView(String, ResourceSet)` anywhere in the code to create an image of the AST graph.
You can take several snapshots without deleting the previous ones.
The pause button in the view will suppress programmatically triggered snapshots.

When taking snapshots, the Xtext resources should not be modified in any way by the graph view, in particular, proxies won’t be resolved.
If they are it is a bug.

The graph view is intended for small test code and is expected to be customized in the source code to suit a particular debugging use case (e.g. to show more / other information in the graph).
Therefore it won't work well / won't scale on large code bases and does not support all conceivable use cases out of the box.
Main entry point for customizations is class `EMFGraphProvider`.


=== API Compare

Shows compare results, i.e. the difference between an API definition project and its implementation.

=== Performance Graphs

Shows some performance measurements of typical tasks such as builds.

=== Source Mapping

Shows source maps, i.e. the relation between N4JS source code and the generated plain JavaScript code.

=== Xpect View

Shows result of an Xpext run, may be used to submit bug reports.
