////
Copyright (c) 2019 NumberFour AG and others.
All rights reserved. This program and the accompanying materials
are made available under the terms of the Eclipse Public License v1.0
which accompanies this distribution, and is available at
http://www.eclipse.org/legal/epl-v10.html

Contributors:
  NumberFour AG - Initial API and implementation
////

= Assistance
:find:
:experimental:

In this chapter we describe all kind of tools assisting the user when writing code, i.e. content assist, quickfixes, quick assists, etc.

WARNING: Not all features are yet implemented!

[[sec:Content_Assist]]
[.language-n4js]
== Content Assist

Content assist may change the document at various places at once. In those cases, it is important to prevent flickering in the editor. The FQNImporter provides a blue print how to adjust line numbers properly and scroll the viewport of the current editor to minimize flickering in the UI.

Completions not listed here as they are provided by template proposals:

1.  Classifier declaration template proposal
2.  Function declaration template proposal
3.  Getter/Setter pair template proposal

[[sec:Complete_Keywords]]
===  Complete Keywords

Complete keyword which are syntactically correct at a given location. Do not suggest completions which would lead to wrong code.

Keywords that contain only a single character are not proposed since they would pollute the proposal window and don’t offer added value.

Special attention has to be given to operators. Since they are modelled in the grammar and not as cross references, their validaty is purely syntactically. That is, there is no generic facility in Xtext, that allows to filter unapplicable operators as there is for cross references.

[[sec:Complete_Annotations]]
===  Complete Annotations

Annotations can be proposed depending on the following elements or the context.

[[sec:Complete_Identifier_Reference]]
===  Complete Identifier Reference

References to identifiers can be automatically completed. This is even true if the declaration is not imported yet, as the import may be automatically added as well.

.Complete identifier references
--
The IDE supports auto-completion of an identifier referencing to a declaration.

1.  Complete type references.
2.  Complete function references.
3.  Complete variable references.
4.  Complete parameter references.
5.  If necessary, imports are added automatically to complete reference $r$ to declaration $D$.
+
Precondition::
-
Postcondition::
+
[%hardbreaks]
$              \spc bind(r, D) $
$              \spc \iff $
$              \spc r.name = D.name $
$              \spc D \in r.module $
$              \spc \lxor $
$              \spc \exists \texttt{NamedImportSpecifier} NIS: $
$              \spc WIS.importDecl.importedModule = D.module $
$              \spc  \lor \exists \texttt{WildcardImportSpecifier} WIS: $

Description::
  There might be multiple declarations $D$ in project (or in dependent projects) with $D.name=r.name$. If the declaration $D$ is not local, then a named import may be created by the content assist:

  ..  If the declaration $D$ is local, no import is created
  ..  If an import enabling access to the declaration already exists, no other import is created.
  ..  If an alias already exists, the alias name is used, even if the prefix was different when the content assist was activated.
  ..  If the import would conflict with an existing member, an alias is proposed along with the import. Linked editing helps to choose a proper alias.
  ..  All imports from a single module are done within a single import declaration. The exception to this rule are wildcard imports that provide a simple name which is currently unused. In that case, a new import may be necessary to disambiguate the wildcard.

6.  If the identifier reference refers to a function (or method), an opening and a closing parenthesis are appended and
    the cursor is positioned between these two parentheses.
--

[[sec:Complete_Member_Overrides]]
===  Complete Member Overrides

.Complete Member Overrides Inside a classifier
--
A prefix of an inherited member can be used to autocomplete that to a complete declaration.
This is in particular true for methods.
--

[[sec:Constructor_Completion]]
===  Constructor Completion

.Constructor Completion
--
Constructor Completion Based on the declared fields and super constructor, constructor methods can be completed.
--

[[sec:Complete_Function_Expression]]
===  Complete Function Expression with Known Type

.Complete Function Expression
--
If a function expression is used as an argument or assigned to a typed variable, the signature of the function can be derived from the type. This can be used to complete a function expression.
--

[[sec:Complete_Variable_and_Parameter_Names]]
===  Complete Variable and Parameter Names

.Type based completion of Variable and Parameter Names
--
Variable and parameter names can be completed based on the type. Camel case detection is used to propose different variations.
--

Completion of variables references see <<sec:Complete_Identifier_Reference,Complete Identifier Reference>>.

[[sec:Quick_Fixes]]
[.language-n4js]
== Quick Fixes

Quick fixes try to solve issues, i.e. errors or warnings, automatically. This is done by rewriting code, either at the location of the issue or at referenced locations.

In all cases, a quick fix must only be suggested if the following preconditions are fulfilled:

1.  All locations at which modifications have to be done must be writeable.
2.  If bindings are involved, e.g., names are to be changed, all previous bindings must remain similar. This might be more complicated as it seems!

[[sec:N4JS_Issue_Properties]]
=== N4JS Issue User data

As some quick fixes need more information to decide upfront which strategy to use, some issues provide additional data. These properties are defined in the file `IssueUserDataKeys.java` in the `org.eclipse.n4js.validation` package. They can for example be accessed by passing the according key to the `getUserData` method of an `N4JSIssue` instance. They are also available as array based Xtext Issue user data. +

All available user data keys are described for each Issue code in <<sec:N4JS_Issue_Fixes,N4JS Issue Fixes>>.

[[sec:N4JS_Issue_Fixes]]
=== N4JS Issue Fixes

The principle idea is to provide a quick fix for every issue, if it is possible to automatically solve it.

[[sec:Linking_Issues]]
====  Linking Issues

Linking issues are special in that they are created by the standard Xtext linker and use all the same built-in issue code `Diagnostic.LINKING_DIAGNOSTIC`. Therefore, we cannot refer to these issues using one of our custom N4JS issue codes.


Diagnostic.LINKING_DIAGNOSTIC::
``Couldn’t resolve reference to _n_``
.  Add missing import declaration for unresolved name _n_.
[horizontal]
Precondition::
..  An exported identifiable element _e_ with name _n_ exists in another module _m_.
..  _e_ is visible from the given location.
Label::
``Import _n_ - _m_``
Postcondition;;
An import declaration was added such that name _n_ is now resolvable at the given location and bound to _e_.
Description;;
Some important notes:
+
. `A` separate quick fix is proposed for each candidate element instead of having a single generic quick fix for adding imports and showing a dialog later (for example, create two quick fixes “Import class `X` from module M1" and “Import interface `X` from module M2" instead of a single quick fix “Add import for name X"). +
This is unusual for quick fixes, because it means significant work has to be done upfront when creating the quick fix / modification proposals, which raises performance concerns. However,
.. the JDT handles this the same way and
.. this brings the implementation closer to content assist allowing more reuse, therefore this decision was taken.
. For consistency, matching of lower/upper/camel case is to be handled as in code completion during content assist. The same applies to display string formatting, esp. name formatting and coloring of element _e_ and module _m_.
. Note that here we can make more assumptions than during import as part of content assist. For example, we know that the element is not imported yet (otherwise there would not be an error) and there won’t be a need for an alias and linked editing.

[[sec:Import_Issues]]
====  Import Issues

[[sec:Visibility_Issues]]
====  Visibility Issues


VIS_ILLEGAL_MEMBER_ACCESS::
  ``The $memberType$ $member$ is not visible.``

  1.  Change access modifier to protected/public or remove `@Internal` annotation.

  Precondition;;
    The file containing the declaration of $member$ is modifiable
  Postcondition;;
    The access modifier has been changed so that $member$ is visible at issue location.
  User Data;;
    * *ACCESS_SUGGESTION* The most restrictive modifier making the member visible.
    * *DECLARATION_OBJECT_URI* The EObject URI of the member declaration


This table shows the access modifier changes to perform to fix the visibility issue while maintaining the strongest access restrictions possible.

[cols="m,m,m,m,m,m,m"]
|===
.2+^|Access Modifier 6+^| Accessible From
| Inside Module | Inside Project | Vendor Subtypes | Vendor Projects | Other Subtypes | Everywhere

|private |- |project |protected@Internal |public@Internal |protected |public
|project |- |- |protected@Internal |public@Internal |protected |public
|protected@Internal |- |- |- |public@Internal |protected |public
|protected |- |- |- |public@Internal |- |public
|public@Internal |- |- |- |- |public |public
|public |- |- |- |- |- |-
|===

Member access modifier changes for quick fixes

VIS_ILLEGAL_FUN_ACCESS::
  ``The function $f$ is not visible.``

  1.  Change access modifier to protected/public or remove `@Internal` annotation.

  Precondition;;
    –
  Postcondition;;
    The access modifier has been changed so that _f_ is visible at issue location.
  User Data;;
    * *ACCESS_SUGGESTION* The most restrictive modifier making the function visible.
    * *DECLARATION_OBJECT_URI* The EObject URI of the function declaration


VIS_ILLEGAL_TYPE_ACCESS::
  ``The type _T_ is not visible.``

  1.  Change access modifier to protected/public or remove `@Internal` annotation.

  Precondition;;
    –
  Postcondition;;
    The access modifier has been changed so that _T_ is visible at issue location.
  User Data;;
    see VIS_ILLEGAL_FUN_ACCESS


VIS_ILLEGAL_VARIABLE_ACCESS::
  ``The variable _v_ is not visible.``

  1.  Change access modifier to protected/public or remove `@Internal` annotation.

  Precondition;;
    Module containing _v_ is writeable.
  Postcondition;;
    The access modifier has been changed so that _v_ is visible at issue location.
  User Data;;
    see VIS_ILLEGAL_FUN_ACCESS


For type, variable and function visibility issues the following changes have to be made to solve the visibility issue:

[[tab:typeAccessControl]]
.Type,function and variable access modifier changes for quick fixes
[cols="m,^m,m,m,m"]
|===
.2+^h|Access Modifier 4+h| Accessible From
^h| Module h| Project h| Vendor h| World

|private |- |export project |export public@Internal |export public
|project |- |export project |export public@Internal |export public
|export project |- ^|- |export public@Internal |export public
|export public@Internal |- ^|- ^|- |export public
|export public |- ^|- ^|- |export public
|===

[[sec:Classifier_Issues]]
====  Classifier Issues


CLF_EXTEND_FINAL::

 ``Cannot extend final class _C_.``

  1.  Remove `@Final` annotation in class _C_

  Precondition;;
    –
  Postcondition;;
    $\lnot C.final$


CLF_OBSERVABLE_MISSING::
``Class $e_0$ extends observable class $e_1$ and must therefore be annotated with @Observable.``

  1.  Add `@Obervable` annotation in class $e_0$

  Precondition;;
    –
  Postcondition;;
    $e_0.observable$


CLF_OVERRIDE_ANNOTATION::
``The $e_0$ overriding $e_1$ must be annotated with @Override.``

  1.  Add `@Override` annotation to $e_0$

  Precondition;;
    –
  Label;;
    ``Add @Override``
  Postcondition;;
    $e_0.override$


CLF_OVERRIDE_FINAL::
``The $e_0$ cannot override final $e_1$.``

  1.  Remove `@Final` annotation in $e_1$

  Precondition;;
    –
  Postcondition;;
    $\lnot e_1.final$


CLF_OVERRIDE_VISIBILITY::
  ``The $e_0$ cannot reduce the visibility of $e_1$.``

  1.  Set access modifier of $e_0$ to access modifier of $e_1$

  Precondition;;
    –
  Postcondition;;
    $e_0.acc == e_1.acc$


CLF_OVERRIDE_NON_EXISTENT::
 ``The $e_0$ $e_1$ must override or implement a $e_0$ from a super class, consumed role or implemented interface.``

  1.  Remove `@Override` annotation in $e_1$

  Precondition;;
    –
  Label;;
    ``Remove @Override``
  Postcondition;;
    $\lnot e_1.override$


CLF_REDEFINED_TYPE_NOT_SAME_TYPE::
  ``Type of $e_0$ must equal type of $e_1$ $e_2$.``

  1.  Set declared type of $e_0$ to declared type of $e_2$

  Precondition;;
    –
  Postcondition;;
    $\tau e_0 = e_2$
CLF_REDEFINED_MEMBER_TYPE_INVALID::
  ``Type of $e_0$ does not conform to $e_2$ $e_1$: $e_3$.``

  1.  Set declared type of $e_0$ to declared type of $e_1$

  Precondition;;
    –
  Postcondition;;
    $\tau e_0 = e_1$
CLF_REDEFINED_METHOD_TYPE_CONFLICT::
  ``Signature of $e_0$ does not conform to $e_1$ $e_2$: $e_3$.``

  1.  Set declared type of $e_0$ to declared type of $e_2$

  Precondition;;
    –
  Postcondition;;
    $\tau e_0 = e_2$
CLF_MISSING_IMPLEMENTATION::
``Class _C_ must either be defined abstract or implement $m$.``

  1.  Declare _C_ as abstract

  Precondition;;
    –
  Postcondition;;
    $C.abstract$


CLF_ABSTRACT_BODY::
 ``Abstract methods do not specify a body.`` for method _M_

  1.  Remove abstract annotation from method.

  Precondition;;
    –
  Postcondition;;
    $\lnot M.abstract$


CLF_ABSTRACT_MISSING::
 ``The abstract $e_0$ $e_1$ in class _C_ can only be defined in an abstract class.``

  1.  Declare _C_ as abstract

  Precondition;;
    –
  Postcondition;;
    $C.abstract$
  Multi appliable;;
    false


CLF_MISSING_BODY::
 ``The $e_0$ $e_1$ has to have either a body or must be defined abstract.``

  1.  Declare $e_1$ as abstract

  Precondition;;
    –
  Postcondition;;
    $e_1.abstract$



CLF_EXT_EXTERNAL_N4JSD::
  ``$e_0$ declared as external have to be placed in a file with file extension ’n4jsd’.``

  1.  Remove external annotation

  Precondition;;
    –
  Postcondition;;
    $\lnot e_0.external$
  2.  Change module file extension to n4jsd

  Precondition;;
    –
  Postcondition;;
    module file extension is n4jsd
CLF_NOT_EXPORTED_NOT_PRIVATE::
  ``A $e_0$ with visibility $e_1$ must be marked as exported.``

  1.  Export $e_0$

  Precondition;;
    –
  Postcondition;;
    $e_0$ is exported

[[sec:Function_Issues]]
====  Function Issues

[horizontal]
FUN_BLOCK::
  ``Functions declarations should not be placed in blocks. Use a function expression or move the statement to the top of the outer function.`` with function $F$

  1.  Change function declaration to function expression

  Precondition;;
    –
  Postcondition;;

[math]
++++
\beginalign
                & \exists \texttt{Variable}\ v \in F.vee: \\
                &   \hspace{3em}v.name = F \\
                &   \hspace{3em} \land v.expr.\mu = \texttt{FunctionExpression} \\
                &   \hspace{3em} \land v.expr.name = F.name, v.expr.body = F.body
\endalign
++++
  Description;;
    Change function declaration to function expression assigned to variable of the function name

[[sec:Syntax_Issues]]
====  Syntax Issues

AST_STR_FUN_NOT_NESTED::
  ``Functions must only be declared on script level or as part of other expressions``

  1.  Change function declaration to function expression assigned to variable of the function name

  Precondition;;
    –
  Postcondition;;
[math]
++++
\beginalign
                & \exists \texttt{Variable}\ v \in F.vee: \\
                &   \hspace{3em}v.name = F \\
                &   \hspace{3em} \land v.expr.\mu = \texttt{FunctionExpression} \\
                &   \hspace{3em} \land v.expr.name = F.name, v.expr.body = F.body
\endalign
++++

SYN_MODIFIER_BAD_ORDER::
  ``Modifiers should appear in this order: O ``

  1.  Rearrange access modifiers

  Precondition;;
    –
  Postcondition;;
    Modifiers are in order O
  Description;;
    Reorder the access modifiers to match the N4JS compliant order.

[[sec:Conversion_Issues]]
====  Conversion Issues

[[sec:Type_Issues]]
====  Type Issues

TYS_INVALID_TYPE_SYNTAX::
  ``Wrong type syntax: Use 'foo:Type' rather than 'Type foo'.``
  
  1.  Converts type annotation to colon style.

[[sec:Expression_Issues]]
====  Expression Issues

EXP_WRONG_NUMBER_OF_TYPEARGS::
  ``Incorrect number of type arguments for $T$ _C_: expected $tpcount$, got $tacount$.``

  1.  Remove superfluous arguments

  Precondition;;
    $tacount>tpcount$
  Postcondition;;
    $tacount=tpcount$
  Description;;
EXP_NUM_OF_ARGS_TOO_MANY::
  ``Incorrect number of arguments: expected $fpcount$, got $argcount$.``

  1.  Remove superfluous arguments

  Precondition;;
    $argcount>fpcount$
  Postcondition;;
    $argcount=fpcount$
  Description;;
EXP_CAST_UNNECESSARY::
  ``Unnecessary cast from $S$ to $T$``

  1.  Remove cast

  Precondition;;
    –
  Postcondition;;
    cast removed
  Description;;

[[sec:Super_Keyword_Issues]]
====  Super Keyword Issues

[[sec:Quick_Assist]]
== Quick Assist

[[sec:Cleanup_Operations]]
[.language-n4js]
== Cleanup Operations


[[sec:Formatting]]
===  Formatting

[[sec:Organize_Imports]]
===  Organize Imports

Import statements can be cleaned up or automatically inserted by invoking ``Organize Imports``. ``Organize Imports`` is available in the context menu ``Source / Organise imports`` , in menu ``Source > Organize imports`` or by hitting kbd:[Cmd] + kbd:[Option] +kbd:[O] (Win/Linux - kbd:[Ctrl] +kbd:[Alt] +kbd:[O]).

For a valid file without errors, this will result in the following actions:

* Unused named imports will be removed.
* Unused wildcard imports will be removed.
* Bare imports will never be removed.
* In each import statement the imported elements will be lexicographically sorted depending on the imported element’s name.
* All import statements will be lexicographically sorted depending on the module specifier as major and the element name as minor key.
  However, bare imports will always be moved to the front and their order relative to each other will never be changed.
+
NOTE: Since N4JS imports are currently transpiled to ES6 imports and the order of imports in ES6 is significant at runtime,
the above sorting can in certain corner cases change the behavior of the code.
* All import statements will be moved to the top of the file.

For a file with error-conditions of unresolved references, this will result in the automatic actions:

* All ambiguous wildcard imports will be presented in one dialog, requesting the user to resolve the ambiguity.
* Each uniquely resolvable ``unresolved Classifier`` will be added by a named import. The search scope is limited to the dependencies declared in the current project-setup.

No action will be taken, if ...

* a classifier with name `X` is already imported by name from a module `A` and a unknown member of this classifier is marked. Even though the import of `X` from a different module `B` could remove this error, the semantic consequences could not be evaluated. The state will be left as-is.

If more then one option leads to a possible resolution the situation should be clarified using quick-fixes, e.g. if ...

* more then one module provides an element, which would render a formerly unresolved reference to be valid.
* for a wildcard-imported element `X` there are unknown members and a different module provides an element `X` containing the missing members. In such a case a named import of `X` would be proposed, optionally using an alias.

