////
Copyright (c) 2019 NumberFour AG and others.
All rights reserved. This program and the accompanying materials
are made available under the terms of the Eclipse Public License v1.0
which accompanies this distribution, and is available at
http://www.eclipse.org/legal/epl-v10.html

Contributors:
  NumberFour AG - Initial API and implementation
////

= CLI and Execution
:find:


This chapter describes the command line interface of the N4JS headless tool, i.e. mainly the N4JS compiler,
and how to execute N4JS projects.

The headless tool provides goals for a variety of use cases.
Compiling a given project is the most obvious use case.
Other use cases are cleaning a given project or generating the api documentation.
Moreover, the headless tool provides LSP-Server functionality and can be used as an
incremental builder daemon that listens to file system events. 


[[sec:Headless_Compiler]]
[.language-bash]
== Command Line Call

The headless compiler `n4jsc.jar` is invoked via

[source,bash]
----
java -jar n4jsc.jar [GOAL] [DIR(s)] [OPTION(s)]
----

Calling `java -jar n4jsc.jar --help` will print out all available goals and options.



=== Argument GOAL

The headless compiler provides the following goals which are executed on all given n4js projects:
compile (implicit goal)::
   Compiles all n4js files
   
clean::
   Cleans all output folders

lsp::
   Starts an lsp server

api::
   Generates api documentation

watch::
   Starts a compile daemon that watches the file system


If the call of `n4jsc` omits a goal, the implicit goal `compile` is used.


=== Argument DIR(s)

The goal is executed on a set of given projects.
The set is determined by the `DIR(s)` argument, which used to find all relevant n4js projects.


=== Finding projects

For every given directory by the `DIR` argument, the following approach is used to determine the set of all projects.
The approach considers both npm and yarn project file structures.

Firstly, a set of all projects and secondly the set of all their dependencies is determined.
The set of all project is determined as follows:

* Step 1 - Find npm projects:
** check the given directory is a project (ie. contains a package.json)
** if so, go to step 2
** if not, go from the given directory to the parent directory until it is a project:
*** if so, to to step 2
*** if no project could be found: End without any project

* Step 2 - Find yarn projects:
** If the given project is a yarn workspace project, add all projects referenced in property `workspace`
** go to step 3 

* Step 3 - Find dependencies:
** For all projects: Add projects in node_module folders



== NPM n4js-cli

The npm package n4js-cli has the same user API regarding all goals and options.
However, n4js-cli has one extension: the (optional) `n4js-cli.config` file.
In case there exists such a file in the project root directory, it will be picked up by n4js-cli.


=== Configurations of n4js-cli

The `n4js-cli.config` file has a json format and supports following optional configuration properties at the moment.

==== "n4jsc.jar"

This name-value property specifies which `n4jsc.jar` to use.
The value can be 

* a relative file path inside the `bin` folder of the n4js-cli package,
* an absolute file path on the file system
* an URL pointing to a n4jsc.jar.

In case the given `n4jsc.jar` is an URL, the file will be downloaded and saved inside the `bin` folder of the n4js-cli package.
A new folder inside `bin` will be created for every host and path that contains the specified `n4jsc.jar` file.
Otherwise, the given file will be used directly without copying it.

Example::

[source,bash]
----
{
	"n4jsc.jar" : "https://n4-cd-n4ide-storage.s3.amazonaws.com/products/0.23.5.v20200723-0804/n4jsc_0.23.5.v20200723-0804.jar"
}
----


[[sec:Executing_N4JS_Code]]
== Executing N4JS Code

The N4JS compiler generates ES modules (also known as "ESM code"). This means the generated code does not
follow the conventions of AMD, CommonJS, or other module formats but instead makes use of the standard
import and export statements introduced by ECMAScript 2015.

Based on this, there are two main approaches for executing N4JS code in NodeJS:

* using Node's native support for ES modules, by adding `"type": "module"` to the project's `package.json` file.
* using library https://www.npmjs.com/package/esm["esm"], by adding it as a dependency to the `package.json` file and invoking Node with
  the command line option `-r esm`. This will convert the ES modules generated by the N4JS transpiler
  to CommonJS code for node on-the-fly (during module loading).

The first approach is recommended, but since Node imposes certain limitations regarding the use of legacy CommonJS
code from native ESM code this might lead to problems when dealing with older Javascript libraries. In these
cases, the interoperability code emitted by the N4JS transpiler when flag `rewriteCjsImports` is set to `true`
in the project's package.json file, can help in some cases (see Section <<sec:N4JS_Properties>>).
