// Generated by N4JS transpiler; for copyright see original N4JS source file.

(function(System) {
	'use strict';
	System.register([
		'org.eclipse.n4js.spec.tests/src-gen/Ch08_02_01_SuperKeyword/superGetterSetterAccess/remote_static/I1'
	], function($n4Export) {
		var I1, I2;
		I2 = {};
		$n4Export('I2', I2);
		return {
			setters: [
				function($exports) {
					// org.eclipse.n4js.spec.tests/src-gen/Ch08_02_01_SuperKeyword/superGetterSetterAccess/remote_static/I1
					I1 = $exports.I1;
				}
			],
			execute: function() {
				I2.$fieldInit = function I2_fieldInit(spec, mixinExclusion) {
					I1.$fieldInit.call(this, spec, mixinExclusion);
				};
				I2.$methods = {};
				$makeInterface(I2, function(instanceProto, staticProto) {
					var metaClass = new N4Interface({
						name: 'I2',
						origin: 'org.eclipse.n4js.spec.tests',
						fqn: 'Ch08_02_01_SuperKeyword.superGetterSetterAccess.remote_static.I2.I2',
						n4superType: undefined,
						allImplementedInterfaces: [
							'Ch08_02_01_SuperKeyword.superGetterSetterAccess.remote_static.I1.I1'
						],
						ownedMembers: [],
						consumedMembers: [],
						annotations: []
					});
					return metaClass;
				});
			}
		};
	});
})(typeof module !== 'undefined' && module.exports ? require('n4js-node').System(require, module) : System);
//# sourceMappingURL=I2.map
