/**
 * Copyright (c) 2016 NumberFour AG.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *   NumberFour AG - Initial API and implementation
 */
/**
 * Some classes in this package are pre-generated by Xtext, so do not move or rename this package as these classes
 * {@link org.eclipse.n4js.ui.quickfix.N4JSQuickfixProvider} will be generated again.
 */
package org.eclipse.n4js.ui.quickfix;
