////
Copyright (c) 2016 NumberFour AG.
All rights reserved. This program and the accompanying materials
are made available under the terms of the Eclipse Public License v1.0
which accompanies this distribution, and is available at
http://www.eclipse.org/legal/epl-v10.html

Contributors:
  NumberFour AG - Initial API and implementation
////


= Modules: builds


`org.eclipse.n4js.product.build`::
is the product definition for the N4JS-IDE, which is materialized when using the Profile *buildProduct*

`org.eclipse.n4js.product.headless.build`::
is the product definition used in the headless compiler.
This one is not materialized, but repository for its plugins is always created.

`org.eclipse.n4js.jre.linux.gtk.x86_64`::
is the platform specific bundle that contains the JRE for the Linux IDE

`org.eclipse.n4js.jre.macosx.cocoa.x86_64`::
is the platform specific bundle that contains the JRE for the Mac IDE

`org.eclipse.n4js.jre.win32.win32.x86_64`::
is the platform specific bundle that contains the JRE for the Windows IDE
