////
Copyright (c) 2019 NumberFour AG and others.
All rights reserved. This program and the accompanying materials
are made available under the terms of the Eclipse Public License v1.0
which accompanies this distribution, and is available at
http://www.eclipse.org/legal/epl-v10.html

Contributors:
  NumberFour AG - Initial API and implementation
////

= Execution
:find:

The output code generated by the N4JS transpiler can be executed with NodeJS the same way as ordinary
Javascript code. Simply provide the main file on the command line

[source]
----
node src-gen/main.js
----

Implicit import statements generated at the top of output files will make sure that the `n4js-runtime` is
loaded and initialized as early as possible, no matter which output file will be used as entry point.
This is why a dependency to `n4js-runtime` is mandatory for all N4JS projects, except for those with a
project type that disallows the project to contain executable code.

Executing code in a browser is possible by packaging the N4JS project, using common tools such as `webpack`.

Javascript tools such as Babel can be used to fine tune the generated output code for production,
as with plain Javascript code.


== Legacy Considerations on Execution

WARNING: This chapter is outdated.

There are many different use cases for executing N4JS code:

* running project locally
* running tests in CI
* running application in the client
* running processor on the server

All those use cases may differ in their details, but can be divided into general phases:

1.  execution environment preparation
2.  bootstrapping
3.  call to given n4js entry point
4.  shutdown (optional)

When N4JS execution is triggered, proper _Runner_ (see <<sec:Runners-introduction,Runners>>) is selected. In some cases it is done automatically, in others user needs to make a choice. Runner is responsible for perform all required preparations, according to <<sec:N4JS_Project_Execution_And_Linking_Model,N4JS Project Execution And Linking Model>>. Then JS execution environment (e.g. NodeJS, IOJS, Chrome, JavaScriptCore) performs bootstrapping according to <<sec:N4JS_Execution_And_Linking_File>>. As last step of bootstrap phase defend n4js entry point will be called which starts proper n4js execution phase. In some cases there may be shutdown phase, but that is highly dependent on use case and proceeding execution phases.

[[sec:N4JS_Project_Execution_And_Linking_Model]]
[.language-n4js]
=== N4JS Project Execution And Linking Model

N4JS project is compiled to JavaScript language, that in turn can be executed in some JS execution environment, Those environments (e.g. NodeJS, IOJS, Chrome, JavaScriptCore) will differ between each other in terms of JS APIs they expose and way JS code has to be provided to them, or the way it is triggered. We introduced systematic way of describing those features in terms of N4JS projects (see Components and Projects <<sec:N4_Components_and_IDE_Support,Components and IDE Support>>). N4JS project will be of different _PojectType_ that determines project purpose (see Package.json section <<sec:Package_json>>. When we want to execute some N4JS project, we can divide its dependency graph into 4 general areas

1.  User Space, e.g. user code
2.  System Space, e.g N4 Platform APIs
3.  Runtime Space, e.g. EcmaScript APIs
4.  Environment Space, e.g. execution environment APIs

Example of that kind of graph can bee seen on <<fig:od_sampleProjectDependencyGraph>>

[[fig:od_sampleProjectDependencyGraph]]
[.center]
image::{find}images/od_sampleProjectDependencyGraph.svg[title="Sample Project Dependency Graph"]

All dependencies are compile time dependency (as they are checked by the compiler), but _tend_ to weaken, the lower in the dependency graph we are. _User Space_ objects will have strong load time and run time dependency to each other and to the _System Space_. _System Space_ have strong load time and run time dependency to each other and, only runtime dependency to _Runtime Space_. _Runtime Space_ objects should not have any load time dependencies between each other. In some cases they may have weak runtime dependency to each other. In many cases those components are just api definitions that describe execution environment native apis, but may contain polyfills code. _Environment Space_ has no dependency to other components, except the fact different __RuntimeEnvironemnt__s can extend each other (see <<sec:N4_Components_and_IDE_Support>>).

Runner must configure JS execution environment in the way that all above areas of the dependency graph must be either

* provided by execution environment itself (runtime libraries APIs - _n4jsd_ files)
* loaded by defined runtime environment (self initialisation code)
* available to load by environment explicitly (runtime libraries polyfills, system libraries)
* available to load by other implicitly (system libraries, user libraries and projects)

Testers, the same way as runners, must be able to execute n4js code. Main difference is that dependency graph for test case will be usually slightly bigger (dependencies to test libraries), and code that has to be triggered shifts a bit from given project to test library used in test code of tested project. Extending previously used example with test elements is shown in figure <<fig:od_sampleTestProjectDependencyGraph2>>.


[[fig:od_sampleTestProjectDependencyGraph2]]
[.center]
image::{find}images/od_sampleTestProjectDependencyGraph.svg[title="Sample Test Project Dependency Graph"]

[[fig:runners-testers]]
[.center]
image::{find}images/runners-testers.svg[title="Runners and Testers"]

[[subsec:N4JS_Execution_With_NodeJS]]
[.language-n4js]
==== N4JS Execution With NodeJS
This example shows in-depth details of N4JS code execution with NodeJS runner.

In the workspace we have `Client` with `foo.n4js` that imports `bar.n4js` from `UserLib` that is also in the workspace.
Those N4JS files use some ES5 APIs , e.g. `Math.random()` and `setTimeout()`. Those APIs are `Global` so there is 
no impicit import, still they make user projects depend on runtime library `n4js-runtime-es2015`.
Assuming user selects `foo.n4js` file for execution, the NodeRunner in the IDE will:

* create working directory in temp folder, e.g. `/var/temp/N4JSNodeRun123/`
* create `node_modules` folder inside working directory, to which projects will be linked
* generate script, e.g. `n4jsELF.js` that will be responsible for booting execution (see <<sec:N4JS_Execution_And_Linking_File>>)
* runner will put `/var/temp/N4JSNodeRun123/node_modules` into `NODE_PATH`
* execute `/var/temp/N4JSNodeRun123/n4jsELF.js` with NodeJS

For example with NodeJS environment if all projects from dependency graph are accessible in local file system, their
paths would need to be put in NodeJS _NODE_PATH_ environment variable. In addition to configuring execution environment
_Runner_ generates N4JS Elf file that is used by environment to bootstrap n4js execution 
(see <<sec:N4JS_Execution_And_Linking_File>>).
[[fig:od_sampleNodeProjectExecution]
[.center]
image::{find}images/od_sampleNodeProjectExecution.svg[title="Sample NodeJS Project Execution"]
