// Generated by N4JS transpiler; for copyright see original N4JS source file.

(function(System) {
	'use strict';
	System.register([], function($n4Export) {
		var C;
		C = function C() {};
		return {
			setters: [],
			execute: function() {
				$makeClass(C, N4Object, [], {
					bar: {
						value: function bar___n4() {
							return this;
						}
					},
					foo: {
						value: function foo___n4() {
							return this.bar();
						}
					}
				}, {}, function(instanceProto, staticProto) {
					var metaClass = new N4Class({
						name: 'C',
						origin: 'org.eclipse.n4js.spec.tests',
						fqn: 'Ch04_12_ThisType.ThisReturnType_CorrectReturn.C',
						n4superType: N4Object.n4type,
						allImplementedInterfaces: [],
						ownedMembers: [
							new N4Method({
								name: 'bar',
								isStatic: false,
								jsFunction: instanceProto['bar'],
								annotations: []
							}),
							new N4Method({
								name: 'foo',
								isStatic: false,
								jsFunction: instanceProto['foo'],
								annotations: []
							})
						],
						consumedMembers: [],
						annotations: []
					});
					return metaClass;
				});
			}
		};
	});
})(typeof module !== 'undefined' && module.exports ? require('n4js-node').System(require, module) : System);
//# sourceMappingURL=ThisReturnType_CorrectReturn.n4js.map
