// Generated by N4JS transpiler; for copyright see original N4JS source file.

(function(System) {
	'use strict';
	System.register([], function($n4Export) {
		var Cls;
		Cls = function Cls() {
			this.fieldPublic = undefined;
			this.fieldProject = undefined;
			this.fieldPrivate = undefined;
		};
		$n4Export('Cls', Cls);
		return {
			setters: [],
			execute: function() {
				$makeClass(Cls, N4Object, [], {
					fieldPublic: {
						value: undefined,
						writable: true
					},
					fieldProject: {
						value: undefined,
						writable: true
					},
					fieldPrivate: {
						value: undefined,
						writable: true
					}
				}, {}, function(instanceProto, staticProto) {
					var metaClass = new N4Class({
						name: 'Cls',
						origin: 'org.eclipse.n4js.spec.tests',
						fqn: 'Ch11_01_Array_and_Object_Destructuring.destructuring_typesystem.M.Cls',
						n4superType: N4Object.n4type,
						allImplementedInterfaces: [],
						ownedMembers: [
							new N4DataField({
								name: 'fieldPublic',
								isStatic: false,
								annotations: []
							}),
							new N4DataField({
								name: 'fieldProject',
								isStatic: false,
								annotations: []
							}),
							new N4DataField({
								name: 'fieldPrivate',
								isStatic: false,
								annotations: []
							})
						],
						consumedMembers: [],
						annotations: []
					});
					return metaClass;
				});
			}
		};
	});
})(typeof module !== 'undefined' && module.exports ? require('n4js-node').System(require, module) : System);
//# sourceMappingURL=M.map
