/**
 * Copyright (c) 2016 NumberFour AG.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *   NumberFour AG - Initial API and implementation
 */
grammar org.eclipse.n4js.ts.TypeExpressions with org.eclipse.n4js.common.unicode.Unicode hidden(WS, ML_COMMENT,
SL_COMMENT, EOL)

import "http://www.eclipse.org/emf/2002/Ecore" as ecore
import "http://www.eclipse.org/n4js/ts/Types"
import "http://www.eclipse.org/n4js/ts/TypeRefs"

// ****************************************************************************************************
// N4JS versions of type references and expressions, also used by Types.xtext
//
// References:
//
// [ECM15]	ECMAScript 2015 Language Specification / ISO/IEC (ECMA-262, 6th Edition).
//			International Standard.
//			http://www.ecma-international.org/publications/ files/ECMA-ST/Ecma-262.pdf
//
// ****************************************************************************************************

/*
 * cf. N4JSSec §4
 * Depending on where the type references is used, not all possible variants are allowed.
 * This is however checked by the validator in order to
 * 1) provide better error messages
 * 2) simplify grammar
 *
 * Constraints:
 * UnionElementTypeRef: no AnyType, no Void, union itself must not be dynamic
 * FParTypeRef: no Void
 * ReturnTypeRef: everything, but no dynamic
 * // in N4JS:
 * VarTypeRef: no Void, i.e.
 * AttributeTypeRef: no Void
 */
TypeRef returns TypeRef:
	IntersectionTypeExpression ({UnionTypeExpression.typeRefs+=current} ("|" typeRefs+=IntersectionTypeExpression)+)?;

IntersectionTypeExpression returns TypeRef:
	ArrayTypeExpression ({IntersectionTypeExpression.typeRefs+=current} ("&" typeRefs+=ArrayTypeExpression)+)?;

ArrayTypeExpression returns TypeRef:
	  ({ParameterizedTypeRef} typeArgs+=WildcardOldNotationWithoutBound arrayTypeExpression?='[' ']' =>({ParameterizedTypeRef.typeArgs+=current} arrayTypeExpression?='[' ']')*)
	| ({ParameterizedTypeRef} '(' typeArgs+=Wildcard ')' arrayTypeExpression?='[' ']' =>({ParameterizedTypeRef.typeArgs+=current} arrayTypeExpression?='[' ']')*)
	| PrimaryTypeExpression =>({ParameterizedTypeRef.typeArgs+=current} arrayTypeExpression?='[' ']')*;

PrimaryTypeExpression returns TypeRef:
	( ArrowFunctionTypeExpression
	| IterableTypeExpression
	| TypeRefWithModifiers
	| "(" TypeRef ")"
	);

TypeRefWithModifiers returns StaticBaseTypeRef:
	TypeRefWithoutModifiers =>followedByQuestionMark?='?'?;

TypeRefWithoutModifiers returns StaticBaseTypeRef:
	  ((ParameterizedTypeRef | ThisTypeRef) => dynamic?='+'?)
	| TypeTypeRef
	| FunctionTypeExpressionOLD
	| UnionTypeExpressionOLD
	| IntersectionTypeExpressionOLD;

TypeRefFunctionTypeExpression returns StaticBaseTypeRef:
	  ParameterizedTypeRef
	| IterableTypeExpression
	| TypeTypeRef
	| UnionTypeExpressionOLD
	| IntersectionTypeExpressionOLD;

TypeArgInTypeTypeRef returns TypeArgument:
	  ParameterizedTypeRefNominal
	| ThisTypeRefNominal
	| WildcardOldNotation;


ThisTypeRef returns ThisTypeRef:
	ThisTypeRefNominal | ThisTypeRefStructural;

ThisTypeRefNominal returns ThisTypeRefNominal:
	{ThisTypeRefNominal} 'this';

ThisTypeRefStructural returns ThisTypeRefStructural:
	definedTypingStrategy=TypingStrategyUseSiteOperator
	'this'
	('with' TStructMemberList)?;

FunctionTypeExpressionOLD returns FunctionTypeExpression:
	{FunctionTypeExpression}
	'{'
	('@' 'This' '(' declaredThisType=TypeRefFunctionTypeExpression ')')?
	'function'
	('<' ownedTypeVars+=TypeVariable (',' ownedTypeVars+=TypeVariable)* '>')?
	'(' TAnonymousFormalParameterList ')' ColonSepReturnTypeRef?
	'}';

ArrowFunctionTypeExpression returns FunctionTypeExpression:
	=>({FunctionTypeExpression} '(' TAnonymousFormalParameterList ')' '=>') returnTypeRef=PrimaryTypeExpression;

// TODO extract FormalParameterContainer and use returns FormalParameterContainer instead of wildcard
fragment TAnonymousFormalParameterList* :
	(fpars+=TAnonymousFormalParameter (',' fpars+=TAnonymousFormalParameter)*)?
;

/**
 * Used in type expressions, name is optional.
 */
TAnonymousFormalParameter:
	variadic?='...'? (=>(name=BindingIdentifier<Yield=false> ->ColonSepTypeRef) | typeRef=TypeRef)
	DefaultFormalParameter
;

/**
 * Used in Types language only.
 */
TFormalParameter:
	variadic?='...'? name=BindingIdentifier<Yield=false> ColonSepTypeRef
	DefaultFormalParameter
;

/**
 * Default initializers in FunctionTypeExpressions or TFunctions
 * are necessary to specify optional formal parameters. Hence, their
 * initializer expression is rather uninteresting and limited by validations
 * to 'undefined'. The shorthand form, that is omitting the initializer, is supported.
 */
fragment DefaultFormalParameter*:
	(hasInitializerAssignment?='=' astInitializer=TypeReferenceName?)?
;

UnionTypeExpressionOLD returns UnionTypeExpression:
	{UnionTypeExpression}
	'union' '{' typeRefs+=TypeRef (',' typeRefs+=TypeRef)* '}';

IntersectionTypeExpressionOLD returns IntersectionTypeExpression:
	{IntersectionTypeExpression}
	'intersection' '{' typeRefs+=TypeRef (',' typeRefs+=TypeRef)* '}';

ParameterizedTypeRef returns ParameterizedTypeRef:
	ParameterizedTypeRefNominal | ParameterizedTypeRefStructural;

ParameterizedTypeRefNominal returns ParameterizedTypeRef:
	(
		TypeReference
	|	{VersionedParameterizedTypeRef}
		TypeReference VersionRequest
	)
	(-> TypeArguments)?
;

ParameterizedTypeRefStructural returns ParameterizedTypeRefStructural:
	(
		definedTypingStrategy=TypingStrategyUseSiteOperator TypeReference
	|	{VersionedParameterizedTypeRefStructural}
		definedTypingStrategy=TypingStrategyUseSiteOperator TypeReference VersionRequest
	)
	(-> TypeArguments)?
	('with' TStructMemberList)?
;

IterableTypeExpression returns ParameterizedTypeRef:
	iterableTypeExpression?='['
	(
		typeArgs+=EmptyIterableTypeExpressionTail
	|	typeArgs+=TypeArgument (',' typeArgs+=TypeArgument)* ']'
	);

EmptyIterableTypeExpressionTail returns Wildcard:
	{Wildcard} ']';

fragment VersionRequest*: requestedVersion=VERSION;

fragment TypeReference *:
	declaredType=[Type|TypeReferenceName]
;

fragment TypeArguments *:
	'<' typeArgs+=TypeArgument (',' typeArgs+=TypeArgument)* '>'
;

fragment TStructMemberList*:  '{' (astStructuralMembers+=TStructMember (';'|',')?)*  '}';

/**
 * All TMembers here are only used in ParameterizedTypeRefStructural references
 * Most type references are optional. However, in the types language (n4ts), these
 * references are NOT optional.
 */
TStructMember:
	  TStructGetter
	| TStructSetter
	| TStructMethod
	| TStructField;

TStructMethod:
	=>
	({TStructMethod}
		TypeVariables?
	    name=IdentifierName '('
	)
	TAnonymousFormalParameterList ')' ColonSepReturnTypeRef?
;

// TODO extract TypeVariableContainer to be used here
fragment TypeVariables*:
	'<' typeVars+=TypeVariable (',' typeVars+=TypeVariable)* '>'
;

fragment ColonSepDeclaredTypeRef*:
	':' declaredTypeRef=TypeRef
;

fragment ColonSepTypeRef*:
	':' typeRef=TypeRef
;

fragment ColonSepReturnTypeRef*:
	':' returnTypeRef=TypeRef
;

TStructField:
	name=IdentifierName (optional?='?')? ColonSepTypeRef?
;

TStructGetter:
	=> ({TStructGetter}
	'get'
	name=IdentifierName)
	(optional?='?')?
	'(' ')' ColonSepDeclaredTypeRef?
;

TStructSetter:
	=> ({TStructSetter}
	'set'
	name=IdentifierName)
	(optional?='?')?
	'(' fpar=TAnonymousFormalParameter ')'
;

TypingStrategyUseSiteOperator returns TypingStrategy:
	'~' ('~' | STRUCTMODSUFFIX)?;

TypingStrategyDefSiteOperator returns TypingStrategy:
	'~';

terminal STRUCTMODSUFFIX:
	('r' | 'i' | 'w' | '\u2205') '~'
;

TypeTypeRef returns TypeTypeRef:
	{TypeTypeRef}
	('type' | constructorRef?='constructor')
	'{' typeArg=TypeArgInTypeTypeRef '}';

TypeReferenceName:
	IDENTIFIER ('.' IDENTIFIER)*;

TypeArgument returns TypeArgument:
	Wildcard | TypeRef;

Wildcard:
	WildcardOldNotation
|	WildcardNewNotation;

WildcardOldNotation returns Wildcard:
	=> ({Wildcard} '?') (('extends' declaredUpperBound=TypeRef) | ('super'
	declaredLowerBound=TypeRef))?;

WildcardOldNotationWithoutBound returns Wildcard:
	{Wildcard} '?';

WildcardNewNotation returns Wildcard:
	(usingInOutNotation?='out' declaredUpperBound=TypeRef)
|	(usingInOutNotation?='in' declaredLowerBound=TypeRef);

TypeVariable returns TypeVariable:
	(declaredCovariant?='out' | declaredContravariant?='in')?
	name=IDENTIFIER ('extends' declaredUpperBound=TypeRef)?;

/*
 * [ECM11] (7.6, pp. 17)
 * Identifier :: IdentifierName but not ReservedWord
 * ReservedWord :: Keyword | FutureReservedWord | NullLiteral | BooleanLiteral
 */
BindingIdentifier <Yield>:
	IDENTIFIER
	// yield as identifier as of [ECM15] (11.6.2, pp. 165)
	| <!Yield> 'yield'
	| N4Keyword
;

IdentifierName:
	IDENTIFIER | ReservedWord | N4Keyword
;

IdentifierNameWithDash:
	IDENTIFIER_WITH_DASH
;

ReservedWord:
	// Keywords as of [ECM15] (11.6.2, pp. 165)
	'break' | 'case' | 'catch' | 'class' | 'const' | 'continue' | 'debugger' | 'default' | 'delete'
	| 'do' | 'else' | 'export' | 'extends' | 'finally' | 'for' | 'function' | 'if' | 'import'
	| 'in' | 'instanceof' | 'new' | 'return' | 'super' | 'switch' | 'this' | 'throw' | 'try'
	| 'typeof' | 'var' | 'void' | 'while' | 'with' | 'yield'
	// null literal
	| 'null'
	// boolean literal
	| 'true' | 'false'
	// Future Reserved Word as of [ECM15] (11.6.2.2, pp. 166)
	// | 'await' /* reserved word only if parse goal is module - compromise: allow as identifier and validate */
	| 'enum';

N4Keyword:
	'get' | 'set'
	| 'let'
	| 'project'
	| 'external' | 'abstract' | 'static'
	| 'as' | 'from' | 'constructor' | 'of' | 'target'
	| 'type' | 'union' | 'intersection'
	| 'This' | 'Promisify'
	// future reserved keyword in [ECM15] only in modules, we add additional validation
	| 'await'
	// async is not a reserved keyword, i.e. it can be used as a variable name
	| 'async'
	// future reserved keywords in [ECM15], restricted via static semantic in [ECM15]
	| 'implements' | 'interface'
	| 'private' | 'protected' | 'public' // package not used in N4JS
	// definition-site variance
	| 'out'
;


terminal IDENTIFIER:
	IDENTIFIER_START IDENTIFIER_PART*;

terminal IDENTIFIER_WITH_DASH:
	IDENTIFIER_START IDENTIFIER_PART+ ('-' IDENTIFIER_PART+)+;

terminal INT returns ecore::EBigDecimal:
	DECIMAL_INTEGER_LITERAL_FRAGMENT;

terminal ML_COMMENT:
	ML_COMMENT_FRAGMENT;

terminal SL_COMMENT:
	'//' (!LINE_TERMINATOR_FRAGMENT)*;

terminal EOL:
	LINE_TERMINATOR_SEQUENCE_FRAGMENT;

terminal WS:
	WHITESPACE_FRAGMENT+;

terminal fragment UNICODE_ESCAPE_FRAGMENT:
	'\\' ('u' (
		HEX_DIGIT (HEX_DIGIT (HEX_DIGIT HEX_DIGIT?)?)?
	  | '{' HEX_DIGIT* '}'?
	)?)?;

terminal fragment IDENTIFIER_START:
	  UNICODE_LETTER_FRAGMENT
	| '$'
	| '_'
	| UNICODE_ESCAPE_FRAGMENT;


terminal fragment IDENTIFIER_PART:
	  UNICODE_LETTER_FRAGMENT
	| UNICODE_ESCAPE_FRAGMENT
	| '$'
	| UNICODE_COMBINING_MARK_FRAGMENT
	| UNICODE_DIGIT_FRAGMENT
	| UNICODE_CONNECTOR_PUNCTUATION_FRAGMENT
	| ZWNJ
	| ZWJ;

// Intentionally unused to get rid of bogus lexer errors when
// the input contains an incomplete variadic?='...' keyword, e.g. ..)
terminal DOT_DOT:
	'..'
;

terminal VERSION returns ecore::EBigDecimal:
	'#' WS* INT
;
