/**
 * Copyright (c) 2016 NumberFour AG.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *   NumberFour AG - Initial API and implementation
 */
package org.eclipse.n4js.npmexporter.validation

import org.eclipse.n4js.utils.NLS

/**
 * Issue code facility generated by Xtend-active annotation.
 * In case messages.properties is modified, you must update this class by re-triggering the compilation (Simply
 * insert a space and save, undo the change and save again. That way the SCM is not polluted.)
 */
@NLS(propertyFileName="messages")
class ExporterIssueCodes {}
