// Generated by N4JS transpiler; for copyright see original N4JS source file.

import 'n4js-runtime'

export function MyClass() {
	this.field = undefined;
}
$makeClass(MyClass, N4Object, [], {
	field: {
		value: undefined,
		writable: true
	}
}, {}, function(instanceProto, staticProto) {
	var metaClass = new N4Class({
		name: 'MyClass',
		origin: 'lsp-command-clean',
		fqn: 'Module/MyClass',
		n4superType: N4Object.n4type,
		allImplementedInterfaces: [],
		ownedMembers: [
			new N4DataField({
				name: 'field',
				isStatic: false,
				annotations: []
			})
		],
		consumedMembers: [],
		annotations: []
	});
	return metaClass;
});
const c = new MyClass();
c;
//# sourceMappingURL=Module.map
