/*
 * generated by Xtext 2.13.0
 */
package org.eclipse.n4js.json.ide

import com.google.inject.Guice
import org.eclipse.n4js.json.JSONRuntimeModule
import org.eclipse.n4js.json.JSONStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class JSONIdeSetup extends JSONStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new JSONRuntimeModule, new JSONIdeModule))
	}
	
}
